#!/usr/bin/env bash
# Usage: build-and-run
# Build the application from source and run it in a docker container using a
# default set of parent colors.
set -o errexit
set -o pipefail
set -o nounset
trap 'echo "$0: line $LINENO: exit status of last command: $?" 1>&2' ERR

this_dir=$(cd -P "$(dirname "$0")" && pwd)
config_file="$this_dir/../parent-colors.json"
container_config_file="/opt/color-id/$(basename "$config_file")"

docker build --tag color-id "$this_dir/.."
echo
docker run \
  --rm \
  --interactive \
  --volume "$config_file:$container_config_file:ro" \
  color-id "$container_config_file"
